/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRetailerRouteImport } from './routes/_authenticated/retailer'
import { Route as AuthenticatedPickupsRouteImport } from './routes/_authenticated/pickups'
import { Route as AuthenticatedDeliveriesRouteImport } from './routes/_authenticated/deliveries'
import { Route as AuthenticatedCoordinatorRouteImport } from './routes/_authenticated/coordinator'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRetailerRoute = AuthenticatedRetailerRouteImport.update({
  id: '/retailer',
  path: '/retailer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPickupsRoute = AuthenticatedPickupsRouteImport.update({
  id: '/pickups',
  path: '/pickups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeliveriesRoute = AuthenticatedDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoordinatorRoute =
  AuthenticatedCoordinatorRouteImport.update({
    id: '/coordinator',
    path: '/coordinator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coordinator': typeof AuthenticatedCoordinatorRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/pickups': typeof AuthenticatedPickupsRoute
  '/retailer': typeof AuthenticatedRetailerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coordinator': typeof AuthenticatedCoordinatorRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/pickups': typeof AuthenticatedPickupsRoute
  '/retailer': typeof AuthenticatedRetailerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/coordinator': typeof AuthenticatedCoordinatorRoute
  '/_authenticated/deliveries': typeof AuthenticatedDeliveriesRoute
  '/_authenticated/pickups': typeof AuthenticatedPickupsRoute
  '/_authenticated/retailer': typeof AuthenticatedRetailerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/coordinator'
    | '/deliveries'
    | '/pickups'
    | '/retailer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/coordinator' | '/deliveries' | '/pickups' | '/retailer'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/coordinator'
    | '/_authenticated/deliveries'
    | '/_authenticated/pickups'
    | '/_authenticated/retailer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/retailer': {
      id: '/_authenticated/retailer'
      path: '/retailer'
      fullPath: '/retailer'
      preLoaderRoute: typeof AuthenticatedRetailerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pickups': {
      id: '/_authenticated/pickups'
      path: '/pickups'
      fullPath: '/pickups'
      preLoaderRoute: typeof AuthenticatedPickupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deliveries': {
      id: '/_authenticated/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof AuthenticatedDeliveriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coordinator': {
      id: '/_authenticated/coordinator'
      path: '/coordinator'
      fullPath: '/coordinator'
      preLoaderRoute: typeof AuthenticatedCoordinatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCoordinatorRoute: typeof AuthenticatedCoordinatorRoute
  AuthenticatedDeliveriesRoute: typeof AuthenticatedDeliveriesRoute
  AuthenticatedPickupsRoute: typeof AuthenticatedPickupsRoute
  AuthenticatedRetailerRoute: typeof AuthenticatedRetailerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCoordinatorRoute: AuthenticatedCoordinatorRoute,
  AuthenticatedDeliveriesRoute: AuthenticatedDeliveriesRoute,
  AuthenticatedPickupsRoute: AuthenticatedPickupsRoute,
  AuthenticatedRetailerRoute: AuthenticatedRetailerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
